### ISSUE TITLE
goals buffer not in dedicated window in 3-pane mode

### ISSUE THREAD

**Issue by hendriktews** [ProofGeneral/PG#121]
When I start PG in 3-window mode, the _goals_ buffer is not in a dedicated window (do M-: (window-dedicated-p) to find out). This means emacs will happily display other stuff in that window. Is that really intended?

**Comment by cpitclaudel** [comment]
Could it be company-coq's fault? It sometimes needs to show things in the goal buffer's window, so it has to undedicate it, and it doesn't restore the dedication after that.

**Comment by hendriktews** [comment]
Clément Pit--Claudel <notifications@github.com> writes:

> Could it be company-coq's fault? It sometimes needs to show things in

No, this is for PG only.

**Comment by Matafou** [comment]
I will push a quick fix but function proof-display-and-keep-buffer actually needs some refactoring to comply better with window policy, then some code may be factorized between this function and proof-layout-windows.

**Comment by Matafou** [comment]
Fixed.

I also made the behavior of PG less intrusive when looking for a window to display something. In short: try to reuse pg buffers instead of reusing user buffers. I made a single commit because these two are linked: if we make goals and response dedicated then the scripting buffer is sometimes hidden by display-buffer.

Please reopn if you think the behaviour is not satisfying.
