### ISSUE TITLE
Quick compilation mode is not saved

### ISSUE THREAD

**Issue by RalfJung** [ProofGeneral/PG#142]
## Steps to reproduce:

* In the "Coq - Auto Compilation" menu, select "quick, no vio2vo"
* In "Coq - Settings", select "Save settings"
* Quit and restart emacs

## Expected behavior

The auto compilation setting should persist

## Actual behavior

The auto compilation setting is reset to the default, "no quick". Inspecting `~/.emacs` reveals that nothing new has been saved there:
```
;; Custom (managed) Settings
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-PDF-mode t)
 '(TeX-auto-save t)
 '(TeX-insert-braces nil)
 '(TeX-parse-self t)
 '(TeX-source-correlate-mode t)
 '(TeX-source-correlate-start-server t)
 '(column-number-mode t)
 '(company-coq-prettify-symbols nil)
 '(coq-compile-before-require t)
 '(coq-compile-parallel-in-background t)
 '(coq-one-command-per-line nil)
 '(default-input-method "math")
 '(electric-indent-mode nil)
 '(fill-column 80)
 '(global-auto-revert-mode t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(mf-display-padding-height 75)
 '(preview-auto-cache-preamble t)
 '(preview-default-preamble
   (quote
    ("\\RequirePackage["
     ("," . preview-default-option-list)
     "]{preview}[2004/11/05]" "\\PreviewEnvironment{mathparpagebreakable}")))
 '(preview-scale-function 1.4)
 '(proof-follow-mode (quote followdown))
 '(proof-next-command-insert-space nil)
 '(proof-splash-enable nil)
 '(proof-three-window-enable t)
 '(reftex-plug-into-AUCTeX t)
 '(show-paren-mode t)
 '(standard-indent 4)
 '(tab-stop-list (quote (4 8)))
 '(tool-bar-mode nil))
```

**Comment by hendriktews** [comment]
Thanks for the report - I forgot about this. For now you have to
use customize-variable on coq-compile-quick and set it there - or
hardwire it in your .emacs file.

Hendrik

**Comment by hendriktews** [comment]
The root cause of the problem is that `proof-menu-entry-for-setting' works only for some simple types and `coq-compile-quick' has a composite radio type. Therefore I cannot use defpacustom to define coq-compile-quick. If I would, `proof-menu-define-settings-menu' would deliver an easy-menu description with a nil element and the easy-menu call in `proof-menu-define-specific' would choke on it.

Therefore I am using defcustom to define `coq-compile-quick' and there is no entry for coq-compile-quick in `proof-assistant-settings' and the save menu item skips coq-compile-quick.

I see two solutions. The first one follows the spirit of defpacustom and involves enhancing `proof-menu-entry-for-setting' such that it generates submenus for composite types, especially for radio types. Then we could use defpacustom and possibly using :pggroup to define some submenus in the settings menu.

The second solution is to patch `proof-settings-vars' to include an additional list of variables to save and include `coq-compile-quick' and others there.

I tend to the second solution, because it is much simpler and it gives us more control over the menu layout.

@cpitclaudel @Matafou Opinions?

**Comment by cpitclaudel** [comment]
I like your second solution better.  t should be easy to patch proof-settings-vars right after the defcustom.

**Comment by Matafou** [comment]
+1
P.

2017-01-17 15:34 GMT+01:00 Clément Pit--Claudel <notifications@github.com>:
