### ISSUE TITLE
Failures in Unicode test script 

### ISSUE THREAD

**Issue by psteckler** [ProofGeneral/PG#164]
Some of the Unicode features in coq/example-tokens.v don't display correctly.

If you load that file into PG, and enable Unicode tokens via `Proof-General | Quick Options | Display | Unicode tokens`, the Greek delta with subscript 1 appears as Roman text. Also, the \_alpha and alpha\_ examples appear as Roman text.

**Comment by Matafou** [comment]
Seems linked to the fact that it is font-lockified.
P.

2017-03-03 20:52 GMT+01:00 psteckler <notifications@github.com>:

**Comment by cpitclaudel** [comment]
Does anymore use that anymore?

**Comment by psteckler** [comment]
We can query Coq Club to know.

**Comment by psteckler** [comment]
I notice there are some Coq Unicode tokens used for Software Foundations, used just to show items in bold.

**Comment by psteckler** [comment]
I think the issue with the subscripts is that the regexp to find the preceding token isn't matching. If you put in a space to mark the end of the word, you get the Unicode/Greek character.

If I open the `*scratch*` buffer, put in the word "delta", move the point to the beginning, and run `(re-search-forward unicode-tokens-token-match-regexp nil t)`, I get a non-`nil` result. If instead I put in "delta__", I get nil.

**Comment by psteckler** [comment]
Seems to be fixed by 06fd76163b857a056ac44e7437efa17656f06e5b.

**Comment by Matafou** [comment]
The problem came frmo the pfolloqing problem: token should be tokenized only if they are not in the middle of something. so that:

philosophi is not tokenized but
phi_loso_phi is tokenized

The generic code does something about that but it did not deal correctly with "_".

I fixed it this way: tokens made of only letters should be augmented by \\< and \\> to allow tokenization only if the token is surrounded by anything but letters. Tokens made of identifiers (letters _' etc) should be augmented by \\_< and \\_>.

Seems to work now.
And thanks to @psteckler for fixing my commit in the wrong branch :)
