### ISSUE TITLE
PG prints infomsgs twice in some cases

### ISSUE THREAD

**Issue by JasonGross** [ProofGeneral/PG#214]
Perhaps I'm using an outdated version of PG and that's the problem, but here's the behavior I see:

Given this in my document:
```coq
Goal True.
  idtac. idtac 1.
```

If I evaluate this buffer to the end, I get two `1`s in the `*response*` buffer, and the `*coq*` buffer looks like this:
```
Welcome to Coq jgross-Leopard-WS:/home/jgross/Downloads/coq/coq-master,master (d9f79d97dbc503e149cba2df1b228a94d7ac970b)

<prompt>Coq < 3 || 0 < </prompt>Add Search Blacklist "Private_" "_subproof".

<prompt>Coq < 4 || 0 < </prompt>Set Printing Depth 50 .

<prompt>Coq < 5 || 0 < </prompt>Remove Search Blacklist "Private_" "_subproof".  Add Search Blacklist "Private_" "_subproof".

<prompt>Coq < 6 || 0 < </prompt>
<prompt>Coq < 7 || 0 < </prompt>Set Printing Width 83.

<prompt>Coq < 8 || 0 < </prompt>Set Silent.

<prompt>Coq < 9 || 0 < </prompt>Goal True.

<prompt>Unnamed_thm < 10 |branch| 0 < </prompt>idtac.

<prompt>Unnamed_thm < 11 |branch| 0 < </prompt>Unset Silent.

<prompt>Unnamed_thm < 13 |branch| 0 < </prompt>idtac 1.
<infomsg>1</infomsg>
1 subgoal (ID 1)

  ============================
  True

<prompt>Unnamed_thm < 14 |branch| 0 < </prompt>
```

However, if I evaluate sentence by sentence, I get only a single `1`, and my `*coq*` buffer shows this:

```
Welcome to Coq jgross-Leopard-WS:/home/jgross/Downloads/coq/coq-master,master (d9f79d97dbc503e149cba2df1b228a94d7ac970b)

<prompt>Coq < 3 || 0 < </prompt>Add Search Blacklist "Private_" "_subproof".

<prompt>Coq < 4 || 0 < </prompt>Set Printing Depth 50 .

<prompt>Coq < 5 || 0 < </prompt>Remove Search Blacklist "Private_" "_subproof".  Add Search Blacklist "Private_" "_subproof".

<prompt>Coq < 6 || 0 < </prompt>
<prompt>Coq < 7 || 0 < </prompt>Set Printing Width 83.

<prompt>Coq < 8 || 0 < </prompt>Goal True.
1 subgoal (ID 1)

  ============================
  True

<prompt>Unnamed_thm < 9 |branch| 0 < </prompt>idtac.
1 subgoal (ID 1)

  ============================
  True

<prompt>Unnamed_thm < 10 |branch| 0 < </prompt>idtac 1.
<infomsg>1</infomsg>
1 subgoal (ID 1)

  ============================
  True

<prompt>Unnamed_thm < 11 |branch| 0 < </prompt>
```

-----

Why is PG doubling the display of infomsgs?

**Comment by psteckler** [comment]
The bug is present in the latest PG.

**Comment by psteckler** [comment]
There's a variable `proof-shell-urgent-message-marker` which gets set to the offset of the \*coq\* buffer just beyond the last "urgent message", like an `infomsg`, but it wasn't getting used.

The following change in `coq/coq.el` cures the issue here, though I don't know if it's the right fix:
```
@@ -416,7 +416,7 @@ We update `proof-shell-urgent-message-marker' to point to last message found.
 This is a subroutine of `proof-shell-filter'."
   (let ((pt (point)) (end t)
        lastend laststart
-       (initstart (max  (marker-position proof-shell-urgent-message-scanner)
+       (initstart (max  (or (marker-position proof-shell-urgent-message-marker) 1)
                         (marker-position scomint-last-input-end))))
     (goto-char initstart)
```
By printing out the value of `initstart`, I can see that it doesn't change sometimes across calls to the shell filter, so the same piece of the \*coq\* buffer is scanned twice. With the fix here, `initstart` seems to be ratcheted up for each call.

**Comment by Matafou** [comment]
I think `proof-shell-urgent-message-scanner` is better to use in this case but indeed it seems not set to the right value. I hve committed something to set it to the end of the last urgent message.

Since this function is a slight modification of a generic function (that also has this bug) we may change the generic one as well if it happens to be a good fix.
