### ISSUE TITLE
Add PG to MELPA?

### ISSUE THREAD

**Issue by mrkkrp** [ProofGeneral/PG#222]
It would be nice if we could make it installable via MELPA, like all other packages.

**Comment by mrkkrp** [comment]
Would be nice indeed.

**Comment by pmetzger** [comment]
Another vote for this. Having PG installable via MELPA would be terrific.

**Comment by anton-trunov** [comment]
AFAIU, we need to add something like this
```elisp
(proof-general
 :repo "ProofGeneral/PG"
 :fetcher github
 :files ("*"))
```
to https://github.com/melpa/melpa/tree/master/recipes.

Is there anything else that needs to be done? (CC @Matafou @erikmd @cpitclaudel @DavidAspinall).

**Comment by erikmd** [comment]
@anton-trunov Publishing a MELPA package for PG is indeed something we'd really want to do; @cpitclaudel has already worked on this topic with his PR #157; but regarding what remains to do I'd say it is not really a matter of technical issue, but rather a kind of dilemma regarding which version of PG should be put forth (namely, `master` or `async`): Paul had proposed to

**Comment by rgrinberg** [comment]
Isn't there a make statement?

**Comment by erikmd** [comment]
@anton-trunov Publishing a MELPA package for PG is indeed something we'd really want to do! @cpitclaudel has already worked on this topic with his PR #157; but regarding what remains to do I'd say it is not really a matter of technical issue, but rather a kind of dilemma regarding which version of PG should be put forth (namely, `master` or `async`): before leaving Paul had proposed in the [wiki](https://github.com/ProofGeneral/PG/wiki/PG-xml-and-Melpa) to publish the `async` version in MELPA. But this has been somewhat delayed and this version turns out to be not stable enough for the moment to be published this way...
Maybe what we could do anyway is to publish the `master` version on MELPA for the moment, and either:

1. replace it with the `async` version when it will be more refined and tested (hopefully before end-2018), for example by merging `async` in `master` (so that only MELPA package would be created);
2. or publish sooner (not necessarily now but before it is fully stable) the `async` version as a MELPA package called `proof-general-nextgen` or so, that would rely on the other branch of this repo (so two MELPA packages would be created).

I'd have a slight preference for 2. as it would facilitate the installation of `async` for users that want to try the newest version of PG, but the technical issue that could arise is the difficulty to support both packages installed at the same time... but maybe this can be worked around?

@cpitclaudel @Matafou what's your opinion on this?

**Comment by erikmd** [comment]
@rgrinberg
> Isn't there a `$ make` call in there to install PG?

Actually `make` just amounts to byte-compiling PG, which would be performed by the MELPA machinery itself IINM. Therefore, unlike Emacs+OCaml packages such as Merlin for example, using a full-blown `Makefile` compilation won't be necessary for PG...

**Comment by Matafou** [comment]
I am not keen of solution 2 until async branch works better, for now on people would be very disappointed. Does someone have time to work on this during summer. I guess if we don't do that now we never will. I really want to but I *really* don't have time for that for the next month I am afraid. I can try to help a bit.

**Comment by pmetzger** [comment]
Would it be possible just to put the main branch into melpa for now? Surely this will cause no harm, and right now, it will make it far far easier for people to install proof general.

**Comment by Chobbes** [comment]
Proof general should _really_ be on MELPA by this point. It's easy to update a package on melpa, so I would say it should just point to the master branch, and then when async is done and gets merged into the master branch, everybody will get an update.

It's one of the last packages that has to be manually installed, and I think that's pretty bad considering a lot of Coq users are forced into the emacs life --- it gives these people a negative impression.

**Comment by erikmd** [comment]
@pmetzger @Chobbes thanks for your comments! Publishing on MELPA has indeed become paramount for an emacs package such as PG. As I said earlier, there were some hesitation related to the choice of the branch to put forth, but I think we now all agree to stick to `master` for the time being (and merge `async` later on).

So @cpitclaudel @Matafou I propose to prepare such a PR to submit PG on MELPA very soon, unless @cpitclaudel wishes to look after that himself this week-end (as Clément had been strongly involved in #157 for making ProofGeneral MELPA-compatible). Please tell me.

**Comment by cpitclaudel** [comment]
> So @cpitclaudel @Matafou I propose to prepare such a PR to submit PG on MELPA very soon

That would be very nice (thanks!). I've been too busy to work on this.
I'd suggest basing things off the existing work, and pinging me if you run into anything problematic :)

**Comment by erikmd** [comment]
Thanks Clément! I started working on this in the `prepare-melpa` branch, but I'll need to pursue this tomorrow as a pass on the docstrings will probably be necessary to comply with [melpa guidelines](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md).

**Comment by erikmd** [comment]
FYI I've just submitted the MELPA recipe in this PR: melpa/melpa#5700

**Comment by Matafou** [comment]
The "checkdoc" box is not checked. Is there something to do about it?

P.

**Comment by erikmd** [comment]
Hi @Matafou 
> The "checkdoc" box is not checked. Is there something to do about it?

Good question :) I actually did not check this box to just mean that even if I did a pass on all files, there are some remaining warnings... As the PG codebase is very large (70 .el files), it was not easy to address all of them (e.g. some docstrings didn't mention all parameters of the function, which triggered a checkdoc warning, and sometimes it was not trivial to infer their semantics; so I had decided to keep these as is).

Thus the unchecked box didn't mean "it is not done at all", but "it is not 100% complete"... I hope this will be OK for MELPA maintainers.

Have a nice day, Erik

**Comment by Matafou** [comment]
hopefully so... I will try to have a look but certainly in some cases I won't be able to complete docstrings...

**Comment by erikmd** [comment]
The PR melpa/melpa#5700 has just been merged, so ProofGeneral is now available in MELPA :)

I'll close this issue as soon as I have updated the installation instructions in the README and the PG website.

**Comment by Matafou** [comment]
Cool! Thank you very much for the work Erik.
You may add a line saying to remove from config files anything about a previously manually installeg pg  before switching to melpa.

**Comment by erikmd** [comment]
Hi @Matafou,
> You may add a line saying to remove from config files anything about a previously manually installeg pg before switching to melpa.

Good idea! actually I'll open a PR so you can comment on the prose :)

**Comment by pmetzger** [comment]
It would still be good to complete the docstrings work and to clean up the namespace used by pg. Perhaps that should be a distinct pair of issues to track the work?
