### ISSUE TITLE
Tip of master is broken on Coq 8.4pl*

### ISSUE THREAD

**Issue by JasonGross** [ProofGeneral/PG#24]
It tries to pass ```-Q `pwd` ```, which Coq 8.4 does not recognize.

**Comment by cpitclaudel** [comment]
Is the `coq-pre-v85` option related to this?

**Comment by Matafou** [comment]
Did you try to put

-Q pwd ""

in _CoqProject? It should work with both coq_makefile and pg.

P.


2016-01-05 21:43 GMT+01:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by JasonGross** [comment]
`-Q` is not a valid argument to `coqtop` 8.4pl6.  `coq_makefile` interprets `-Q` as a filename in 8.4pl6.

**Comment by Matafou** [comment]
Ho sorry,

yes I guess I need to have a look at v8.4 compatibility, for coq prog
args at least, and hopefully for auto compilation. Did you set
coq-pre-v85?


P..


2016-01-07 23:33 GMT+01:00 Jason Gross <notifications@github.com>:

**Comment by JasonGross** [comment]
No, I did not try setting coq-pre-v85, but I would prefer to not have to change variables every time I switch Coq versions.  Can you set it automatically by parsing the output of `coqc -v`?

**Comment by Matafou** [comment]
Yes I can, but it has to be done each time coq is launched. Otherwise coqc
may not be in the path, or the one in the path may not be the one you have
in mind.

Another solution (which also deal with coq-prog-name itself) is to have a
.dir-local.el file to set it this variable project by project:

((nil
  . ((eval
      . (progn
  (setq coq-pre-v85 t)
          (setq coq-prog-name "/foo/bar/coq-8.4/bin/coqtop"))))))

P.

2016-01-08 0:59 GMT+01:00 Jason Gross <notifications@github.com>:

**Comment by cpitclaudel** [comment]
Hey Pierre,

Do you want to try to implement this together this week-end? Many people are going to want to move from 8.4 to 8.5 in the next year; for all these people, it would be really nice to have good support for switching coq versions dynamically.

Parsing the _CoqProject file is really fast, so I think one way to go would be to delay all parsing until just before calling executable. This way we can dynamically set `coq-pre-v85` by ourselves.

The difficulty is that our users may have configured coq-prog-args, and we don't want to override that customization. With the proposed scheme we would never write to coq-prog-args; instead, we'd just have a function that uses coq-prog-args if it has been customized, and reads the current _CoqProject otherwise. Do you see an issue with this strategy?

**Comment by Matafou** [comment]
Le vendredi 8 janvier 2016, Clément Pit--Claudel <notifications@github.com>
a écrit :

> Hey Pierre,
>
> Do you want to try to implement this together this week-end? Many people
> are going to want to move from 8.4 to 8.5 in the next year; for all these
> people, it would be really nice to have good support for switching coq
> versions dynamically.
>
> Parsing the _CoqProject file is really fast, so I think one way to go
> would be to delay all parsing until just before calling executable. This
> way we can dynamically set coq-pre-v85 by ourselves.
>
Actually the project file is re-read each time Coq is launched in a new
file already.


> The difficulty is that our users may have configured coq-prog-args, and we
> don't want to override that customization. With the proposed scheme we
> would never write to coq-prog-args; instead, we'd just have a function that
> uses coq-prog-args if it has been customized, and reads the current
> _CoqProject otherwise. Do you see an issue with this strategy?
>
>
> coq-prog-args set via file variables do take priority over _coqproject
already.

The only thing we need is to also check for Coq version at the last moment.
I am sorry I cannot have a lot of time during weekends (my 3 children
wouldn't allow). Feel free to start and I will try to help.

P.

**Comment by cpitclaudel** [comment]
> Actually the project file is re-read each time Coq is launched in a new
file already.

Indeed. My suggestion is to delay this even further, to when we start coqtop.

>  The only thing we need is to also check for Coq version at the last moment. I am sorry I cannot have a lot of time during weekends (my 3 children wouldn't allow). 

Nor should they! Enjoy the week-end :)

> Feel free to start and I will try to help.

I'll take a look. Thanks for all your help Pierre! :)

**Comment by cpitclaudel** [comment]
I've made some progress with this (see #26), but I need help to review the code and to understand some things. I posted notes there.

**Comment by cpitclaudel** [comment]
Ok, ready for testing I think. The code in #26 now redetects the Coq compiler every time we are asked for coqtop prog args.

**Comment by Matafou** [comment]
My test with coq-8.5 are OK.
Green for me.

2016-01-09 23:44 GMT+01:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by JasonGross** [comment]
Seems to work for me; thanks!

**Comment by cpitclaudel** [comment]
Just merged #26, so I'll close this :)
