### ISSUE TITLE
Should we bind C-c C-j in terminals?

### ISSUE THREAD

**Issue by cpitclaudel** [ProofGeneral/PG#31]
`C-c C-RET` (proof-goto-point) doesn't work in shells. Should we bind `C-c C-j` instead on TTYs?

**Comment by Matafou** [comment]
IMHO yes.
P.

2016-01-15 0:14 GMT+01:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by JasonGross** [comment]
I generally bind `C-c RET`, so that `C-c C-RET` works regardless of where I am.

**Comment by cpitclaudel** [comment]
Does your terminal differenciate RET and C-j?

**Comment by JasonGross** [comment]
`C-c C-j` gives "No active hole"

**Comment by cpitclaudel** [comment]
Can you do `C-h k C-c C-j` and `C-h k C-c C-RET`?

**Comment by JasonGross** [comment]
```
C-c C-j runs the command holes-set-point-next-hole-destroy, which is
an interactive compiled Lisp function in `holes.el'.

It is bound to C-c C-j, <menu-bar> <Holes> <Jump To Active Hole>.

(holes-set-point-next-hole-destroy)

Moves the point to current active hole (if any and if in current buffer).
Destroy it and makes the next hole active if any.
```

```
C-c RET runs the command company-coq-proof-goto-point, which is an
interactive compiled Lisp function in `company-coq.el'.

It is bound to C-c RET, C-c <C-return>, <menu-bar> <Proof-General>
<Goto Point>.

(company-coq-proof-goto-point &rest ARGS)

Pass ARGS to `proof-goto-point', hiding company dialog.

[back]
```
(`C-RET` doesn't actually work over mosh at all, but it's easier to teach my fingers to switch back and forth between `C-c C-RET` and `C-c RET` than anything else.)


Using `C-h k C-c C-RET` over ssh in ssh gives `C-c C-^` is not defined.

**Comment by cpitclaudel** [comment]
What a mess.

**Comment by Matafou** [comment]
:) Indeed this is my fault. Holes are my (old) skeleton-like mode. It is
hardly used by anyone other than me I guess, so we can make its shortcuts
different with no harm. And maybe we can remove them completely? It has
more features than company-coq templates but since nobody use them except
me...

Actually I think company-coq should also avoid this shortcut. C-c RET is
something users want to customize (I do: I bind it to dabbrev-expand).

P.






2016-01-18 5:56 GMT+01:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by cpitclaudel** [comment]
Company-Coq doesn't bind `C-c RET` actually (It does bind `C-RET` though, but the Emacs manual only reserved `C-c <letter>` for users, so that seems reasonable)

**Comment by cpitclaudel** [comment]
What does holes do that yasnippet doesn't do? I don't want to lose functionality, but anything we can do to remove some of the maintenance burden is good, I think (that's partly why I used `prettify-symbols-mode` instead of PG's custom solution for unicode math in company-coq)

**Comment by Matafou** [comment]
With holes you can paste things from anywhere (including other frames) in
the currently active hole without going back to it. This allows to build
composite expressions rather easily.

Try:

open a coq file, type "dec" then M-x expand-abbrev. Hopefully (if standard
pg abbrev were loaded) this will create two holes:

decompose [#] #

(alternatively you can create several holes with C-c h and click on the
first one to make it active).

Now select something anywhere, including in another frame/window and type
C-c C-y. It fills the firs hole and make the next one active. Now do it
again... etc.

Maybe there is something similar in yasnippets but I did not see any
documentation on it.

There used to be some meta-ctrl-mouse ways to paste things in active hole
too, but they are broken currently.

P.




2016-01-19 16:34 GMT+01:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by erikmd** [comment]
Hi @cpitclaudel @Matafou @JasonGross I think I've good news regarding this issue:
It is possible to bind `C-c RET` to `'proof-goto-point` without causing any clash with `C-c C-j` (nor with company-coq's default key-bindings IINM) because `RET`actually corresponds to `C-m`, not `C-j`.
This makes sense because the "carriage return" char is ASCII 13, which corresponds to `^M`, i.e. `C-m`.
I'm going to push a PR to add this.
