### ISSUE TITLE
Goal diff support

### ISSUE THREAD

**Issue by cpitclaudel** [ProofGeneral/PG#381]
Hi all,

@jfehrle is finalizing https://github.com/coq/coq/pull/8301, which adds goal diffs to Coq's output.

company-coq already has a similar option, but it's brittle and it doesn't compare parts of goals and hypotheses.

In XML mode, this new diff highlighting just adds extra tags.  In command line mode, it adds extra colors.
To support this legacy PG, we should make sure to set the `COQ_COLORS` variable to values supported by `ansi-color-apply-region`, and to call that function after inserting goals. `ansi-color-apply-region` uses `ansi-color-apply-overlay-face`, so this shouldn't clash with syntax highlighting.

We might want to bind `ansi-color-names-vector` appropriately as well, to use the standard emacs diff colors.

**Comment by erikmd** [comment]
Hi @cpitclaudel!

When you say
>  In command line mode, it adds extra colors.
> To support this legacy PG […]

Do you mean
- To add support in PG **when emacs is run in tty mode:** <kbd>emacs -nw</kbd>, or just
- To add support in **PG master** (for both GUI and tty) ?

**Comment by jfehrle** [comment]
The discussion just before this point covers the issues fairly well https://github.com/coq/coq/pull/8301#discussion_r212761812

**Comment by erikmd** [comment]
OK! thanks @jfehrle :)

**Comment by jfehrle** [comment]
@erikmd No worries.

**Comment by erikmd** [comment]
Anyway I'm glad that Clément confirmed in this issue that relying on your feature would improve on company-coq's goal-diffing current feature I had told you about at Nice. So we should work on integrating it in PG!
Maybe in both PG master and async?
If yes, @cpitclaudel, shouldn't we tag this issue `pg: proof-shell + async` instead?

**Comment by jfehrle** [comment]
Goal diff support shipped with Coq 8.9 several months ago.  I'd like to see this Coq feature supported in PG, as do the PG users I've talked to.

As I've mentioned elsewhere, I've never used PG, I'm not an emacs user, I haven't done emacs lisp and I don't know how the PG team operates.  I think it would take a long while to learn how to make the changes myself.  I don't expect I'll ever want to make other PG changes.

I'd be delighted if someone with PG development experience is willing to take this on.  I believe the changes would be pretty simple for someone with such experience.

@cpitclaudel, @erikmd is there anyone who might do this work?

**Comment by monnier** [comment]
> Goal diff support shipped with Coq 8.9 several months ago.  I'd like to see
> this Coq feature supported in PG, as do the PG users I've talked to.

A pointer to this feature would be helpful.  I for one don't know what
this refers to.

**Comment by jfehrle** [comment]
The Coq documentation for this feature is here: https://coq.inria.fr/distrib/current/refman/proof-engine/proof-handling.html#showing-differences-between-proof-steps.  The doc includes a couple small screen shots of the feature.

**Comment by jfehrle** [comment]
I'm looking at what's needed to allow ProofGeneral to show proof diffs, considering changes to both Coq and PG.  I'm looking at the PG 'master' branch first.  (I'll look at the 'async' branch later.)

Coq's `-emacs` mode currently adds a few XML-like tags in the output such as `<prompt>`.  It would be simple to mark diff highlights in stdout with tags such as `<diff.added>` and `</diff.added>` when -emacs and Diffs are both enabled.

Non-PG users of this mode would likely need to change their code if they want to enable diffs. 
 
A couple questions:
1. Is Coq's `-emacs` mode intended only (or primarily) for PG?

2. Opening diff tags will match the regexp '<diff.[a-zA-Z\.]+>'  Does Coq allow defining a notation that matches that?  I wasn't sure what conclusion to draw from the experiment below.  It seems unlikely but maybe not impossible for proof step output to include one of the diff tags.  Those proofs, if they exist and are done with PG, should be done with Diffs off.  Alternatively, I could escape non-tag `<` and `&` in the output with (say) `&lt;` and `&amp;` then have PG unescape them.  This would significantly break PG,  forcing PG users to get updated PG to work with an updated Coq.

![image](https://user-images.githubusercontent.com/1253341/56260903-e202cb80-608d-11e9-8da3-9a988033fbaa.png)

![image](https://user-images.githubusercontent.com/1253341/56260891-d6170980-608d-11e9-9005-6a98906d0c07.png)

I'm inclined to generate tags only for diff highlights when both -emacs and Diffs are enabled.  That seems the least disruptive.  And not bother escaping `<` characters since that would also cause some disruption. 
 The async branch already uses XML to communicate with Coq.  Why reinvent the wheel?

Comments?  Is it indeed possible to define a notation that could generate output containing the strings `<diffs.added>` or `</diffs.added>`?

**Comment by Matafou** [comment]
> I'm looking at what's needed to allow ProofGeneral to show proof diffs, considering changes to both Coq and PG. I'm looking at the PG 'master' branch first. (I'll look at the 'async' branch later.)
> 
> Coq's `-emacs` mode currently adds a few XML-like tags in the output such as `<prompt>`. It would be simple to mark diff highlights in stdout with tags such as `<diff.added>` and `</diff.added>` when -emacs and Diffs are both enabled.

Yes it should be ok, the idea is that in any case the emacs buffers shows text with no xml in it, so that copy-pasting is ok.

> Non-PG users of this mode would likely need to change their code if they want to enable diffs.
> 
> A couple questions:
> 
> 1. Is Coq's `-emacs` mode intended only (or primarily) for PG?

Yes. As far as I know nobody uses coqtop -emacs for anything else than pg.

> 2. Opening diff tags will match the regexp '<diff.[a-zA-Z.]+>' Does Coq allow defining a notation that matches that?

Probably yes, but it is highly unlikely.

>  I wasn't sure what conclusion to draw from the experiment below.  It seems unlikely but maybe not impossible for proof step output to include one of the diff tags.  Those proofs, if they exist and are done with PG, should be done with Diffs off.  Alternatively, I could escape non-tag `<` and `&` in the output with (say) `&lt;` and `&amp;` then have PG unescape them.  This would significantly break PG,  forcing PG users to get updated PG to work with an updated Coq.

I don't thing implementing this workaround is worth the effort.

> I'm inclined to generate tags only for diff highlights when both -emacs and Diffs are enabled. That seems the least disruptive. And not bother escaping `<` characters since that would also cause some disruption.

I agree.

> The async branch already uses XML to communicate with Coq. Why reinvent the wheel?

The async branch uses the xml interface provided by coq. It was once meant to become the new master, but it did not reach a sufficient level of maturity. It is currently stalled, to my great disappointment. Indeed if the async was the master today implementing diffs would be trivial.

> Comments? Is it indeed possible to define a notation that could generate output containing the strings `<diffs.added>` or `</diffs.added>`?

It is probably possible but so what? Other special pseudo-xml tags suffer the same problem, I never had any user complaint about it. Maybe we could add a dummy notation using this syntax so that if the user (re)defines it he would be warned?

**Comment by jfehrle** [comment]
Thanks, it helps to get some confirmation on the plan before finishing the code.

**Comment by jfehrle** [comment]
I implemented diff support in PG a couple years ago.  AFAIK this issue should have been closed long ago.

**Comment by Matafou** [comment]
Indeed. Works like a charm btw. Thanks a lot for that!
