### ISSUE TITLE
Consider renaming pg-init.el to proof-general.el, to match MELPA package name

### ISSUE THREAD

**Issue by andersk** [ProofGeneral/PG#385]
I’m using [`use-package`](https://github.com/jwiegley/use-package) with byte-compiled `.emacs`, and the new MELPA `proof-general` package is great because I can lazily load it to cut down Emacs startup time. But `use-package` assumes that the library filename matches the package name, and `proof-site.el` is the only exception I’ve ever encountered, so the configuration is a little more complicated than it could be:

```elisp
(use-package proof-general
  :ensure t
  :no-require t)

(use-package proof-site
  :mode ("\\.v\\'" . coq-mode))
```

If `proof-site.el` were renamed to `proof-general.el`, then one stanza would suffice:

```elisp
(use-package proof-general
  :ensure t
  :mode ("\\.v\\'" . coq-mode))
```

**Comment by cpitclaudel** [comment]
Hmm, interesting.

PG is a bit of a weird package.  It already loads itself lazily, mostly; proof-site just registers a bunch of autoloads (including coq-mode) and a few variables from pg-vars.  In a sense, the whole proof-site is an autoload, and indeed it gets loaded automatically at startup in pg-init.el.

Given this, my intuition would be that the second stanza you posted should be enough; what problems do you run into if you use just that?

**Comment by andersk** [comment]
Just `(use-package proof-site :mode ("\\.v\\'" . coq-mode))` fails to trigger [automatic installation](https://github.com/jwiegley/use-package/#package-installation) of `proof-general` if it’s missing.

Just `(use-package proof-general :ensure t :mode ("\\.v\\'" . coq-mode))` fails with `File mode specification error: (file-missing Cannot open load file No such file or directory proof-general)` if you haven’t run `(package-initialize)`, which I haven’t (saving about 1 second of Emacs startup time).

**Comment by erikmd** [comment]
Thanks @andersk for your suggestion :)
I'd vote :+1: for this renaming, even if this is a non-backward-compatible change (that could cause an issue for PG users updating their installation with Git) because:

1. it appears more natural to write `(use-package proof-general` than `(use-package proof-site`

2. if I'm not mistaken (after taking a quick look at [that code](https://github.com/melpa/melpa/blob/16f79d3ff5a7f9b14d54018f7e8196053f308a85/package-build/package-build.el#L840)) **this change could solve another issue**: the fact that [the description on the MELPA website](https://melpa.org/#/proof-general) is empty...

**Comment by cpitclaudel** [comment]
OK, thanks for testing @andersk .  Shouldn't we rename pg-init, though, rather than proof-site?

**Comment by erikmd** [comment]
@cpitclaudel indeed, maybe that'd be even better to rename pg-init... (and update its Commentary section)

**Comment by andersk** [comment]
Yeah, renaming pg-init would work and sounds like a better idea.
