### ISSUE TITLE
Indentation with "|"

### ISSUE THREAD

**Issue by chaomaer** [ProofGeneral/PG#405]
```
Inductive day: Type :=
  | sunday
```

but when i  type the RET after the "sunday" , the code becomes
```
Inductive day: Type :=
| sunday
```

I hope it still like the above.
is there anyway , thanks.

**Comment by cpitclaudel** [comment]
I think we don't have a way for this. @monnier might be able to help?

**Comment by monnier** [comment]
- Put point right before the line whose indentation you don't like, i.e. right before `|`.
- Type `M-x smie-config-show-indent RET`.  You should then see something like:

        Rules used: :before ":= inductive" -> (column . 2), :before "|" -> 2, :after ":= inductive" -> 2

  Where the last `2` is a bit misleading: it talks about the indentation of `sunday` rather than of the pipe
  (because the pipe is optional).

- Type `M-x smie-config-set-indent RET`.  Then select `after ":= inductive"` and choose 4 (to increase indentation by 2 positions).
- Try the new setting on other lines to make sure it does what you want and doesn't introduce other problems.
- If you decide you like it do `M-x smie-config-save RET`.

This SMIE config business is a bit rough still, and IIRC the saving&restoring wasn't working in previous versions (can't remember when it was fixed, but it might be Emacs-25 or Emacs-26).  So feel free to report bugs and feature requests for it.

**Comment by Matafou** [comment]
I can't reproduce this behaviour, unless the description is wrong about "hitting return after sunday" and means "hitting return after :=" or "hitting tab when on sunday".
Is it he case?

**Comment by Matafou** [comment]
One can already configure this for "match with" expression with variable coq-match-indent (2 by default, 4 to indent more). would it be ok that the same variable also configures the indentation of inductives?
I mean people who like: 
```
match foo with
  | bar
```
are likely to like too:
```
Inductive foo :=
  | bar
```
aren't they?

**Comment by chaomaer** [comment]
@monnier 's solution works well. Thanks all people.
