### ISSUE TITLE
Failure while processing imports

### ISSUE THREAD

**Issue by YaZko** [ProofGeneral/PG#46]
Hi all,
Dutifully following Clément's post over the Coq list, I installed the latest version of PG. The installation went smoothly but I get, despite using Coq 8.4pl6, quite a weird failure when trying to process a Require Import:

Invalid version syntax: '8.5snapshot'

Would anyone know what might be going on?
Best,
Yannick

**Comment by cpitclaudel** [comment]
Hi there,

This is surprising. In general, it help if you use `M-x toggle-debug-on-error` before reporting bugs, as it will give us a stacktrace.

Looking at your problem suggests that you're not actually using 8.4, but rather a version of coq tagged as 85snapshot.  Since that version string is not valid, PG doesn't know what to do with (we do version detection because some things changed from 8.4 to 8.5). 

Questions:
* Where does your version of Coq come from?
* Can you check coq-prog-name? Run `C-h v coq-prog-name RET`. 
* What does `M-x coq-autodetect-version` return?

That being said, I think there's an issue with version autodetection (it doesn't use coq-prog-name, just the plain coqtop). I'll fix it soon.

Clément.

**Comment by cpitclaudel** [comment]
Oh, wait a minute. I think I see something else.

**Comment by cpitclaudel** [comment]
Can you try the version that I just pushed? Thanks for the report!

**Comment by YaZko** [comment]
Hey,
Thanks a lot for the prompt answer! And sorry for the poorly documented report, I took note of the command to run beforehand.
I just built the new version and it fixed the issue!
Thanks again.
Best,
Yannick

**Comment by cpitclaudel** [comment]
Glad it's fixed :) Sorry for the trouble, and thanks for reporting the issue!

**Comment by cpitclaudel** [comment]
?

**Comment by YaZko** [comment]
My bad, I reopened it and was about to post a new issue, but I realized in time the mistake was on my side (a _CoqProject file in the parent directory messing things up).
Sorry for the inconvenience.

**Comment by cpitclaudel** [comment]
No problem :)
