### ISSUE TITLE
Ltac2 rec

### ISSUE THREAD

**Issue by proux01** [ProofGeneral/PG#489]
`Ltac2 rec f x` is colored as if `rec` is the name of the function and `f x` are arguments.

Maybe the same issue with `Ltac2 mutable` (`Ltac2 rec mutable`?) and `Ltac2 Set`.

**Comment by erikmd** [comment]
@CyrilAnac I propose to assign you to this issue:

* Regarding the place to do the changes in PG codebase, FYI this issue is a follow-up of PR #474

* Ideally PG syntax highlighting should support the whole syntax of Ltac2 commands, which are documented at https://coq.github.io/doc/v8.11/refman/proof-engine/ltac2.html

(so as a first step you should probably create (without committing it) your own example of `.v` file containing one example of each Ltac2 command…)
