### ISSUE TITLE
ProofGeneral does not understand vos files

### ISSUE THREAD

**Issue by RalfJung** [ProofGeneral/PG#500]
I have used the coq_makefile-generated Makefile to build the ".vos" files for my development. Those are quicker to build than .vo files, and they are sufficient for Coq to process `Require`.

However, PG does not understand that, so with "build before require" enabled, PG wants to still build all those .vo files. Is there a way to make it build .vos files instead?

**Comment by hendriktews** [comment]
Ralf Jung <notifications@github.com> writes:

> However, PG does not understand that, so with "build before
> require" enabled, PG wants to still build all those .vo files.
> Is there a way to make it build .vos files instead?

I thought I implemented that. Have you tried to configure
coq-compile-vos?

Hendrik

**Comment by RalfJung** [comment]
Ah, I did not see that option, thanks. :) It seems to work well. :D

**Comment by hendriktews** [comment]
Why can't I comment on a closed issue? (Reopened it for the comment - will close again later)

For coq < 8.11 I made `quick-and-vio2vo` the default, because I thought, it would catch most if not all consistency problems, because it now and then compiles everything to vo in the background. For >= 8.11 I didn't dare to make vos compilation the default, because this can leave a lot of errors unnoticed.

Out of curiosity: Have you used `quick-and-vio2vo`?

**Comment by Matafou** [comment]
Sorry I use coq master most of the time so I "use vos" all the time. It works like a charm by the way.

**Comment by Matafou** [comment]
But as always there may be very few users who noticed this feature. Maybe we should advertise?

**Comment by RalfJung** [comment]
> Out of curiosity: Have you used quick-and-vio2vo?

I tried that for a few weeks (some years ago) but then disabled quick again as I kept running into https://github.com/coq/coq/issues/5223, making this effectively useless. That's why I set `coq-compile-quick (quote no-quick)`.

**Comment by anton-trunov** [comment]
>Maybe we should advertise?

@Matafou Indeed, advertizing new features on Disourse / Zulip would be very much appreciated!

**Comment by hendriktews** [comment]
Advertising: For the vos feature, I added documentation and also an entry in CHANGES. I would say the material is almost there, it just needs to be broadcasted...

**Comment by hendriktews** [comment]
> I tried that for a few weeks (some years ago) but then disabled quick again as I kept running into [coq/coq#5223](https://github.com/coq/coq/issues/5223)

OK, I believe it should have worked under normal circumstances, but it is probably not worth to investigate...

**Comment by RalfJung** [comment]
Is there also some analog to "vio2vo in background" where PG does the equivalent of `make vok`?

**Comment by hendriktews** [comment]
> Is there also some analog to "vio2vo in background" where PG
> does the equivalent of make vok?

No. Personally I find vok compilation not that useful, because it
stops at the first failing proof (see also coq issue 11479) and
it doesn't produce a vo in case of success. Therefore I thought
about `vos-and-vo`, a background pass that slowly compiles
everything to vo. But this is just an idea.

**Comment by RalfJung** [comment]
I think not producing a .vo is a feature. I just deleted all .vo files from my developments, they are just a waste of space. .vos and .vok are all I need.

**Comment by Matafou** [comment]
I think avoiding this duplication is negligible wrt to compilation time. In contrast parallelism is very significant.
@RalfJung what would be the good ergonomics of vok for you? vos allow to open and work in a file pretty quickly after modifying a dependence. We certainly don't want to wait for vok to be built, but maybe made in the background?

**Comment by RalfJung** [comment]
I have more than half a gigabyte of vo files across various Coq developments, that feels significant. ;)

> what would be the good ergonomics of vok for you? vos allow to open and work in a file pretty quickly after modifying a dependence. We certainly don't want to wait for vok to be built, but maybe made in the background?

Yeah, I was imagining something where it does the check in the background, similar to vio2vo.

**Comment by hendriktews** [comment]
The higher parallelism is a point worth considering.
With deleting all vo files, you potentially ignore some universe constraint violations. This is not a concern?

**Comment by RalfJung** [comment]
> With deleting all vo files, you potentially ignore some universe constraint violations. This is not a concern?

That is okay; we have CI running on each push which does a regular make.
AFAIK, vio2vo has the exact same problem, so it seems PG authors were already okay with such a tradeoff.

**Comment by Matafou** [comment]
> With deleting all vo files, you potentially ignore some universe constraint violations. This is not a concern?
It is a trade of, when developing a proof, say on 3 files A B C with this dependencies: C -> B -> A. 
Say that when ou are working on file A you realise that you need to modify C. Open C with PG, do the modification and maybe script until the en of the file to check that everything is alright. Then close C and go back to A.
Now:
1) if you are only compiling vos you may have broken a proof in B without noticing at all.
2) if you compile vos and vok you will notice the breakage, unless it is universe problem between 2 files.
3) if you compile vo you detect everything but it may be slow.

So I guess if we can give 2) with a background compilation people will switch from 1) to 2) happily. Of course sticking to vo must remain an option if you are paranoïd or doing nasty things with you types.
At the end of the day you need a big fat "make" anyway.

**Comment by hendriktews** [comment]
In the example of @Matafou from yesterday, after modifying C, I would jump back to A and start working there, using vos compilation to process the require commands of A. Until this point it is probably uncontroversial and everybody would prefer to do it this way.

Then, while I am already working in A, I would prefer a slow background compilation that compiles A and B (maybe there is more than one B) to vo. If something fails there, I would see an error popping up while I am working in A.

Instead of vo compilation, you (@RalfJung) would prefer vok compilation, because of disk space and higher parallelism, right? I do understand the disk space argument. However, I am not yet fully able to follow the parallelism argument. After vos compilation, you would be busy in A, making use of the last modification in C. In case this takes long, you would not care about the higher parallelism, because checking all proofs in A and B will be finished before you are finished with your task in A. Otherwise, if it only takes little time until you notice that you need to change a second thing in C, you would not care about the parallelism in proof checking either, because you would interrupt the proof checking in any case and restart it later.

Adding vok checking is probably easy, because, from Proof General point of view, it is almost the same as vio2vo. Adding a background vo compilation is more involved, because vo compilation must respect the dependencies.

**Comment by RalfJung** [comment]
Higher parallelism makes the background checks go faster when "B" is a huge tree of dependencies. I think that is always desirably, in particular of the vos files are built anyway?

**Comment by hendriktews** [comment]
The vok feature is in #543, I am closing the issue again.
