### ISSUE TITLE
Package `ert-async-' is unavailable

### ISSUE THREAD

**Issue by hendriktews** [ProofGeneral/PG#529]
@erikmd : all the recent PR's fail with this message. IMO ert-async is not even needed for the tests. Can we simply delete the code for bootstrapping ert-async in `ci/init-tests.el`?

**Comment by erikmd** [comment]
Hi @hendriktews, thanks for the ping. Actually the issue was not that the package is not available anymore, but the fact that package.el support is broken with Emacs 26.1, due to a TLS bug.

Admittedly we don't really rely on `ert-async` currently, but I'd prefer to keep it to allow for future test-suite enhancements, and I have just opened a PR that does seem to "fix" the issue at stake: PR #530

So I updated the README.md in the same PR, and I will update https://proofgeneral.github.io as well.
