### ISSUE TITLE
Broken (possibly outdated?) setup instructions regarding `coq-prog-name`

### ISSUE THREAD

**Issue by Janno** [ProofGeneral/PG#596]
The instructions in https://proofgeneral.github.io/doc/master/userman/Obtaining-and-Installing/ instruct users to add `-emacs` to their `coq-prog-name` variable:
https://github.com/ProofGeneral/PG/blob/cc5bfd0b5524313313c8e394656cdb5321b62a42/doc/ProofGeneral.texi#L5976

It seems this actually breaks PG, leading to failures such as 
```
proof-activate-scripting: Wrong type argument: stringp, nil
```
or
```
proof-activate-scripting: Starting process: coqtop -emacs -emacs <..more arguments..>...failed
```
on newer versions of PG.

**Comment by Janno** [comment]
Interestingly, starting `coqtop` with two `-emacs` arguments is actually fine. It seems the debug message printed on newer PG versions is missing some quotes around the program name that it actually tries to run. I assume the actual underlying failure is from trying to run `"coqtop -emacs" -emacs`, not `"coqtop" -emacs -emacs"` as it is printed.

**Comment by hendriktews** [comment]
Thanks for the report! Above the only occurrence of `-emacs` I read "The default names for proof assistant binaries may work on your system. If not, ..." in Appendix A. Therefore, I would not say the manual instructs people to add `-emacs`... Did the default names of the binaries not work for you?
I agree that there seems to be a problem with the documentation. Setting `coq-prog-name` as documented should not raise such an error, even in case the default binaries do work.
Have you customized `coq-compile-before-require` or do you see this problem with the default setting of `nil` for this setting?
The latest changes in that part of the manual are from 2000. @Matafou: To me this looks like we forgot to update that part of the manual when we changed the code to add `emacs` as argument.

**Comment by Matafou** [comment]
Indeed this part of the manual needs update.
AFAIK the good answer is: `coq-prog-name` should contain the executable name ONLY, *with no option or argument*, and options should go into the list `coq-prog-args` (and of course `-emacs`  is useless because added by PG anyway but this is indeed innocuous).
That said even this, while correct, is a bit outdated since writing a _CoqProject is better almost in any circumstances and you don't need to care about these variables anymore.
I will try to fix this part of the documentation. Thanks for reporting.
