### ISSUE TITLE
SO question: How can I get `C-c C-n` to format the current line in proof-general coq-mode-map

### ISSUE THREAD

**Issue by erikmd** [ProofGeneral/PG#603]
Reported by [`@azani`](https://stackoverflow.com/users/1243445/azani) on [StackOverflow](https://stackoverflow.com/q/69419117/9164010):

> I'm using proof-general to write Coq proofs.
> 
> When I use `C-c C-n` in a proof, my cursor is moved to the next line, but the current line is not formatted. So for instance, if I type:
> 
> ```
> intros n. <C-c C-n>
> ```
> 
> my cursor moves to the next line, but `intros n.` remains unindented. So I have to go back up a line, go to the end of the line and hit `<RET>` to auto-indent the coq statement. At which point, `proof-general` considers that statement changed and I have to re-run it.
> 
> Ideally, I would line `C-c C-n` to auto-indent the line it is running and to not go to the next line.
> 
> How can I make that happen?

**Comment by monnier** [comment]
Hmm... it seems this was installed, and I guess either I failed to send my comment or it got lost somewhere, but I (thought I) pointed out that the right function to call is `indent-according-to-mode` and also that doing it unconditionally is probably a bad idea (I for one don't expect nor want my lines to be reindented just because I type `C-c C-n`).  I think it should not be enabled by default, but at the very least it should be controlled by a defcustom.

**Comment by monnier** [comment]
Duh, I just see that I was just completely confused (looking at the wrong data after a typo merged the wrong pull request).  Just scratch my previous comment (which I just deleted now).

**Comment by Matafou** [comment]
PR #606 fixes this by allowing indentation in locked region without backtracking.
