### ISSUE TITLE
proof-goto-point is non-idempotent

### ISSUE THREAD

**Issue by aa755** [ProofGeneral/PG#728]
Consider the following file:

```
Definition xx:=0.
Definition yy:=1.
```

When the curser is at the end of the first line, doing `proof-goto-point` toggles between locking/checking the next line and retracting back to the end of the first line.
Based on the documentation, I would expect it to be a no-op when only the first line is locked.

**Comment by hendriktews** [comment]
I don't know why, but when point is at the end of the locked region, proof-goto-point asserts the next command. After that point is inside the locked region and the next proof-goto-point causes a retract. Does this issue cause any inconvenience on your side? Because as a fix I would first only consider to weaken the documentation to manage expectations on the users side.

**Comment by aa755** [comment]
There is not much inconvenience on my side: I can work around it on my side with a wrapper.
